console.log("Hello World!");
var a = 5;
var b = 3;
var s1 = "Hello";
var s2 = "Caroline.";
console.log(a);
console.log(a * b);
console.log(a + b);
console.log(s1 + s2);
console.log(s1 + " " + s2);
console.log("Squared of " + a + " is " + a * a);
